# Generated by Django 4.1.2 on 2022-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=None, help_text="input deadline", null=True
            ),
        ),
    ]
