# Generated by Django 4.1 on 2022-10-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "datetime"]},
        ),
    ]
